spring:
  application:
    name: task2
  r2dbc:
    url: r2dbc:h2:mem:///mydb
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true
    enabled: true