apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    release: !!str {{ .Values.image.tag }}
spec:
  type: LoadBalancer
  ports:
    - name: {{ .Values.ports.name }}
      port: {{ .Values.ports.containerPort }}
      targetPort: {{ .Values.ports.targetPort }}
      protocol: {{ .Values.ports.protocol }}
      appProtocol: {{ .Values.ports.appProtocol }}
  selector:
    app: {{ .Chart.Name }}