global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'task14-job'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['task14:8082']