resilience4j:
  ratelimiter:
    instances:
      rps_limiter:
        limit-for-period: 20
        limit-refresh-period: 1s
        timeout-duration: 0s
      rpm_limiter:
        limit-for-period: 30
        limit-refresh-period: 1m
        timeout-duration: 0s

  circuitbreaker:
    instances:
      default:
        sliding-window-type: time_based
        sliding-window-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 3
        permitted-number-of-calls-in-half-open-state: 1