apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appname }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appname }}
      tier: {{ .Values.tier }}
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
        tier: {{ .Values.tier }}
    spec:
      containers:
        - name: {{ .Values.appname }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
