apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.ports.name }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.ports.targetPort }}
      protocol: {{ .Values.ports.protocol }}
      appProtocol: {{ .Values.ports.appProtocol }}
  selector:
    app: {{ .Chart.Name }}
