spring:
  datasource:
    url: jdbc:h2:mem:userservice
    driverClassName: org.h2.Driver
    username: usr
    password: pwd
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: true

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

server:
  port: 8080
  servlet:
    contextPath: /user-service

passwordEncryptor:
  charset: "UTF-8"
  algorithm: "SHA-512"
  isSalted: true