spring:
  r2dbc:
    url: r2dbc:h2:mem:///userservice;DB_CLOSE_DELAY=-1
    username: usr
    password: pwd
  flyway:
    url: jdbc:h2:mem:userservice;DB_CLOSE_DELAY=-1
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true
    enabled: true

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

server:
  port: 8080
  servlet:
    contextPath: /user-service

resilience4j:
  rateLimiter:
    instances:
      getUserAgeRateLimiterSec:
        limitForPeriod: 20
        limitRefreshPeriod: 1s
        timeoutDuration: 0s
      getUserAgeRateLimiterMin:
        limitForPeriod: 30
        limitRefreshPeriod: 1m
        timeoutDuration: 0s
  circuitbreaker:
    instances:
      getUserAgeCircuitBreaker:
        slidingWindowType: TIME_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 1
        waitDurationInOpenState: 1000
        minimumNumberOfCalls: 3

management:
  server:
    port: 7000
  endpoints:
    web:
      exposure:
        include: '*'

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs-ui

passwordEncryptor:
  charset: "UTF-8"
  algorithm: "SHA-512"
  isSalted: true