spring:
  r2dbc:
    url: r2dbc:h2:mem:///userservice;DB_CLOSE_DELAY=-1
    username: usr
    password: pwd
  flyway:
    url: jdbc:h2:mem:userservice;DB_CLOSE_DELAY=-1
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true
    enabled: true

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

server:
  port: 8080
  servlet:
    contextPath: /user-service

passwordEncryptor:
  charset: "UTF-8"
  algorithm: "SHA-512"
  isSalted: true