spring:
  datasource:
    url: jdbc:h2:mem:userserviceproto;DB_CLOSE_DELAY=-1
    username: usr
    password: pwd
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    url: jdbc:h2:mem:userserviceproto;DB_CLOSE_DELAY=-1
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    baseline-on-migrate: true
    enabled: true

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

grpc:
  server:
    port: 9090