image:
  repository: localhost:5000/helm-demo
  tag: 0.2
  pullPolicy: IfNotPresent

replicaCount: 1
resources:
  limits:
    cpu: 1000m
    memory: 1Gi

ports:
  name: http
  containerPort: 8080
  protocol: TCP
  targetPort: 8080
  appProtocol: http

service:
  type: ClusterIP
  port: 8080

database:
  url: "jdbc:h2:mem:testdb;NON_KEYWORDS=user"
  login: "sa"
  password: ""