services:
  user-service:
    image: user-service
    hostname: user-service
    container_name: user-service
    ports:
      - 8080:8080
      - 7000:7000
    networks:
      - user-service-network
    restart: always

  prometheus:
    image: prom/prometheus
    hostname: prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    networks:
      - user-service-network
    depends_on:
      - user-service
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always

  grafana:
    image: grafana/grafana
    hostname: grafana
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - user-service-network
    depends_on:
      - prometheus
    volumes:
      - ./grafana/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    restart: always

networks:
  user-service-network:
    driver: bridge