global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'metrics-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['metrics-app:8080']