package com.example.otus.models;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Getter;
import lombok.Setter;

@Schema
@Getter
@Setter
@Entity(name = "users")
@Table(name = "users")
public class User {

    @Id
    @Schema(description = "Optional field, autogenerated")
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    @Schema(description = "Name should not be blank")
    private String name;
    @NotNull
    @Schema(description = "Your security password")
    private String password;

    public User() {}

    public User(String name, String password) {
        this.name = name;
        this.password = password;
    }
}
