{
 "title": "user_service_monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": { "query": "label_values(instance)" } },
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"$instance\", job=\"$job\"}) / (1024 * 1024)",
     "legendFormat": "Memory used, Mb"
    },
    {
     "expr": "sum(users_number{instance = \"$instance\", job = \"$job\"})",
     "legendFormat": "Users number"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(process_cpu_usage{instance=\"$instance\", job=\"$job\"})",
     "legendFormat": "Process CPU usage, %"
    },
    {
     "expr": "sum(users_number{instance = \"$instance\", job = \"$job\"})",
     "legendFormat": "Users number"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_sum{instance = \"$instance\", job = \"$job\"}[1m])) / sum(irate(http_server_requests_seconds_count{instance = \"$instance\", job = \"$job\"}[1m]))",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Registered users number",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(users_number{instance=\"$instance\", job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count{instance = \"$instance\", job = \"$job\"}[1m])",
     "legendFormat": "Requests per second"
    }
   ]
  },
  {
   "title": "Requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{instance = \"$instance\", job = \"$job\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed requests, %",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{instance = \"$instance\", job = \"$job\", status =~ \"(4|5).+\"}) / sum(http_server_requests_seconds_count{instance = \"$instance\", job = \"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed requests by codes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (http_server_requests_seconds_count{instance = \"$instance\", job = \"$job\", status =~ \"(4|5).+\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}