spring:

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

server:
  port: 8080
  servlet:
    contextPath: /heads-and-tails