spring:
  application:
    name: out-of-memory-task
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=TRUE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false